name: Build MusicBox

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
      with:
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:v0.12.4

    - name: Cache Docker layers
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: /tmp/.buildx-cache-new
        key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker buildx build \
          --cache-from=type=local,src=/tmp/.buildx-cache-new \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
          -t musicbox-builder \
          --load .

    - name: Build MusicBox
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace musicbox-builder \
        sh -c "cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=/PiZero.cmake && cmake --build build"

    - name: Upload MusicBox binary
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: build_part_app
        path: build/MusicBox
        retention-days: 1

  build_web_interface:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: '21' 

    - name: Install dependencies
      run: |
        cd webroot
        npm install

    - name: Build Vue.js project
      run: |
        cd webroot
        npm run build

    - name: Upload Vue.js build artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: build_part_web
        path: webroot/dist
        retention-days: 1

  combine_artifacts:
    runs-on: ubuntu-latest
    needs: [build_app, build_web_interface]
    steps:
    - name: Download MusicBox binary
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: build_part_app
        path: musicbox

    - name: Download Vue build
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: build_part_web
        path: vue-dist

    - name: Create combined structure
      run: |
        mkdir -p combined/webroot
        cp musicbox/MusicBox combined/
        cp -r vue-dist/** combined/webroot/

    - name: Upload combined artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: MusicBox-Release
        path: combined/